import { v } from "convex/values";

import {
  scanImageBytes,
  scanMediaBytes,
  type AiScanResult,
} from "@/lib/ai-media-scan";

import { action } from "./_generated/server";

export type { AiScanResult };

/**
 * PureWire's anti-AI-content layer.
 *
 * The platform is built on original, human-made work — "say it anyway"
 * means *your* voice, not a machine's. This module scans posts, comments,
 * and stories before they go live:
 *
 * - Text that clearly identifies itself as AI-generated is blocked at
 *   creation with an honest message.
 * - Text that *reads* machine-made (heavy formulaic phrasing, including
 *   bare "as an AI" claims) is flagged for admin review instead of
 *   blocked, so genuine human writing is never rejected on a hunch.
 * - Images with generator metadata baked into the file (Stable Diffusion,
 *   Midjourney, DALL·E, NovelAI, ComfyUI, etc.) are blocked.
 *
 * The raw-byte scanner lives in `src/lib/ai-media-scan.ts` so the browser
 * can pre-scan original bytes BEFORE client-side metadata stripping (see
 * MediaUpload) — stripping EXIF must never also strip the evidence that
 * an image was machine-made. Reading file bytes is only available inside
 * Convex actions, so the media scan is an action that mutations call via
 * `ctx.runAction`.
 */

/**
 * Messages that are overwhelmingly likely to be AI-generated. Each pattern
 * requires the full self-identifying phrase so legitimate human speech
 * like "as an AI researcher" or "I'm an AI engineer" is never blocked.
 */
const HARD_BLOCK_TEXT: RegExp[] = [
  /\bas an ai (?:language model|assistant|chatbot)\b/i,
  /\bi['’]?m an ai (?:language model|assistant|chatbot)\b/i,
  /\bi am an ai (?:language model|assistant|chatbot)\b/i,
  /\bthis (?:post|content|text|paragraph) (?:was|is) (?:written|generated|created|produced) by (?:an )?ai\b/i,
  /\bgenerated by (?:an )?(?:ai|chatgpt|gpt|dall[·e ]|midjourney)\b/i,
  /\bchatgpt (?:wrote|made|generated)\b/i,
];

/**
 * Formulaic phrasing that LLMs overuse — including bare "as an AI" and
 * "I'm an AI" claims, which are demoted here so that a human decides
 * instead of a false-positive block. A post that stacks several of these
 * reads machine-made and is flagged for admin review.
 */
const FORMULAIC_PHRASES = [
  "as an ai",
  "i'm an ai",
  "i am an ai",
  "as a language model",
  "moreover",
  "furthermore",
  "additionally",
  "in conclusion",
  "to summarize",
  "it is important to note",
  "it's important to",
  "it is worth noting",
  "delve",
  "underscore",
  "landscape",
  "in today's",
  "in the ever-evolving",
  "a testament to",
  "at the end of the day",
  "game-changer",
  "seamlessly",
  "cutting-edge",
  "let's dive",
  "it cannot be overstated",
  "it goes without saying",
  "notably,",
  "crucially,",
  "significantly,",
  "all in all",
  "overall,",
];

const MIN_SUSPICIOUS_LENGTH = 120;
const FORMULAIC_HITS_FOR_REVIEW = 5;

/** Scan post/comment/story text for signs of AI generation. */
export function scanText(content: string): AiScanResult {
  const text = content.trim();
  if (text.length === 0) {
    return { status: "clean" };
  }
  for (const pattern of HARD_BLOCK_TEXT) {
    if (pattern.test(text)) {
      return {
        status: "blocked",
        reason: "This reads like AI-generated text, which isn't allowed on PureWire.",
      };
    }
  }
  if (text.length >= MIN_SUSPICIOUS_LENGTH) {
    const lower = text.toLowerCase();
    let hits = 0;
    for (const phrase of FORMULAIC_PHRASES) {
      if (lower.includes(phrase)) {
        hits++;
      }
    }
    if (hits >= FORMULAIC_HITS_FOR_REVIEW) {
      return {
        status: "review",
        reason: "Heavy formulaic phrasing — flagged for a human check.",
      };
    }
  }
  return { status: "clean" };
}

/**
 * Shared validator for the media-scan verdict passed from the client into
 * the post/story mutations. Lives here so both callers stay in sync.
 */
export const AI_MEDIA_STATUS = v.union(
  v.literal("clean"),
  v.literal("review"),
  v.literal("blocked"),
);

export type AiMediaStatus =
  | "clean"
  | "review"
  | "blocked";

/**
 * Scan every image in a media list by reading its bytes from storage.
 * Runs as an action because `storage.get` is only available in actions.
 * Mutations call this via `ctx.runAction`.
 */
export const scanMediaForAi = action({
  args: {
    media: v.array(
      v.object({
        // Dual-mode: a Convex storage id (legacy/fallback) OR an external
        // Cloudinary URL (primary path once CLOUDINARY_* is configured).
        storageId: v.optional(v.id("_storage")),
        url: v.optional(v.string()),
        kind: v.string(),
      }),
    ),
  },
  returns: v.union(
    v.object({ status: v.literal("clean") }),
    v.object({ status: v.literal("review"), reason: v.string() }),
    v.object({ status: v.literal("blocked"), reason: v.string() }),
  ),
  handler: async (ctx, { media }): Promise<AiScanResult> => {
    for (const item of media) {
      let bytes: ArrayBuffer | null = null;
      if (item.url !== undefined) {
        // Cloudinary-backed media: fetch the stored object (actions can fetch;
        // this is the same scan the browser ran pre-upload, re-checked
        // against the exact stored bytes).
        const res = await fetch(item.url);
        if (res.ok) {
          bytes = await res.arrayBuffer();
        }
      } else if (item.storageId !== undefined) {
        const blob = await ctx.storage.get(item.storageId);
        if (blob !== null) {
          bytes = await blob.arrayBuffer();
        }
      }
      if (bytes === null) {
        continue;
      }
      const result: AiScanResult =
        item.kind === "image"
          ? scanImageBytes(bytes)
          : scanMediaBytes(bytes);
      if (result.status !== "clean") {
        return result;
      }
    }
    return { status: "clean" };
  },
});
