import { v } from "convex/values";

import {
  scanImageBytes,
  scanMediaBytes,
  type AiScanResult,
  type C2paInfo,
} from "@/lib/ai-media-scan";
import { scanForRacism } from "@/lib/racism-guard";

import { action } from "./_generated/server";

export type { AiScanResult };

/**
 * PureWire's anti-AI-content layer.
 *
 * The platform is built on original, human-made work — "say it anyway"
 * means *your* voice, not a machine's. This module scans posts, comments,
 * and stories before they go live:
 *
 * - Text that clearly identifies itself as AI-generated is blocked at
 *   creation with an honest message.
 * - Text that *reads* machine-made (heavy formulaic phrasing, including
 *   bare "as an AI" claims) is flagged for admin review instead of
 *   blocked, so genuine human writing is never rejected on a hunch.
 * - Images with generator metadata baked into the file (Stable Diffusion,
 *   Midjourney, DALL·E, NovelAI, ComfyUI, etc.) are blocked.
 *
 * The raw-byte scanner lives in `src/lib/ai-media-scan.ts` so the browser
 * can pre-scan original bytes BEFORE client-side metadata stripping (see
 * MediaUpload) — stripping EXIF must never also strip the evidence that
 * an image was machine-made. Reading file bytes is only available inside
 * Convex actions, so the media scan is an action that mutations call via
 * `ctx.runAction`.
 */

/**
 * Messages that are overwhelmingly likely to be AI-generated. Each pattern
 * requires the full self-identifying phrase so legitimate human speech
 * like "as an AI researcher" or "I'm an AI engineer" is never blocked.
 */
const HARD_BLOCK_TEXT: RegExp[] = [
  /\bas an ai (?:language model|assistant|chatbot)\b/i,
  /\bi['’]?m an ai (?:language model|assistant|chatbot)\b/i,
  /\bi am an ai (?:language model|assistant|chatbot)\b/i,
  /\bthis (?:post|content|text|paragraph) (?:was|is) (?:written|generated|created|produced) by (?:an )?ai\b/i,
  /\bgenerated by (?:an )?(?:ai|chatgpt|gpt|dall[·e ]|midjourney|gemini|bard|grok|claude|deepseek|gpt-4|gpt-4o)\b/i,
  /\bchatgpt (?:wrote|made|generated)\b/i,
  /\bgemini (?:wrote|made|generated|created) (?:this|the above|the following)\b/i,
  /\bbard (?:wrote|made|generated|created) (?:this|the above|the following)\b/i,
  /\bgrok (?:wrote|made|generated|created) (?:this|the above|the following)\b/i,
  /\bclaude (?:wrote|made|generated|created) (?:this|the above|the following)\b/i,
  // "as an AI developed by Google" — the platform's zero-tolerance policy
  // extends to Google's models just like every other provider.
  /\bas an ai developed by (?:google|openai|anthropic|xai|meta)\b/i,
  /\b(?:i am|i['’]m) (?:google['’]s|openai['’]s|anthropic['’]s) ai\b/i,
  // "claude" is deliberately absent from the generic lists — it's also a
  // common human name ("created by Claude" about a person named Claude must
  // never block); only the explicit "Claude wrote this" form above blocks.
  /\b(?:written|generated|created|produced) (?:by|using) (?:openai|chatgpt|gemini|bard|grok)\b/i,
  /\b(?:openai|chatgpt|gemini|bard|grok)[-' ]?(?:generated|wrote|made|created) this\b/i,
];

/**
 * Formulaic phrasing that LLMs overuse — including bare "as an AI" and
 * "I'm an AI" claims, which are demoted here so that a human decides
 * instead of a false-positive block. Each hit adds one point to the
 * machine-made score.
 */
const FORMULAIC_PHRASES = [
  "as an ai",
  "i'm an ai",
  "i am an ai",
  "as a language model",
  "as an llm",
  "moreover",
  "furthermore",
  "additionally",
  "in conclusion",
  "to summarize",
  "in summary",
  "delve",
  "underscore",
  "landscape",
  "in today's",
  "in the ever-evolving",
  "a testament to",
  "at the end of the day",
  "game-changer",
  "seamlessly",
  "seamless",
  "cutting-edge",
  "let's dive",
  "it cannot be overstated",
  "it goes without saying",
  "notably,",
  "crucially,",
  "significantly,",
  "all in all",
  "overall,",
  "it is important to",
  "it's important to",
  "it is worth noting",
  "it's worth noting",
  "robust",
  "leverage",
  "streamline",
  "foster",
  "empower",
  "elevate your",
  "unlock the power",
  "harness the",
  "fast-paced",
  "first and foremost",
  "last but not least",
  "hope this helps",
  "i'd be happy to help",
  "i'd be glad to help",
  "feel free to reach out",
  "feel free to ask",
  "don't hesitate to ask",
  "don't hesitate to reach out",
  "let me know if you have any questions",
  "let me know if you need anything else",
  "i hope this message finds you well",
  "as we move forward",
  "in today's digital",
  "in today's fast-paced",
  "the world of technology",
  "navigate the complexities",
  "game-changing",
  "best-in-class",
  "cutting-edge solutions",
  "state-of-the-art",
  "at its core,",
  "when it comes down to it",
  "the key takeaway",
  "in essence,",
  "ultimately,",
  "it is essential to",
  "it's essential to",
  "it is crucial to",
  "it's crucial to",
  "in today's world",
  "in this fast-paced world",
  "shed light on",
  "in the realm of",
  "when it comes to",
  "it is safe to say",
  "it's safe to say",
  "there's no denying",
  "there is no denying",
];

/**
 * Canned sentence openers LLMs reach for when padding an answer. Each hit
 * adds one point — a human writer rarely opens several sentences with
 * these stock transitions.
 */
const HEDGING_PHRASES = [
  "when it comes to",
  "whether you're",
  "whether you are",
  "it's no secret",
  "let's face it",
  "in the world of",
  "in the realm of",
  "in an era where",
  "as we know",
  "needless to say",
  "in other words",
  "simply put",
  "the bottom line is",
  "one might argue",
  "it is clear that",
  "it's clear that",
  "there is no doubt that",
];

/**
 * Listicle openers — the skeleton of a generated "3 reasons why…" post.
 * Counting distinct ones catches the structure without matching a single
 * innocent "First, " sentence.
 */
const LISTICLE_OPENERS = [
  "first,",
  "first.",
  "second,",
  "second.",
  "third,",
  "third.",
  "fourth,",
  "finally,",
  "finally.",
  "lastly,",
  "lastly.",
  "additionally,",
  "moreover,",
  "in conclusion,",
];

/** Words too common to count toward the repetition signal. */
const STOP_WORDS = new Set([
  "the", "a", "an", "and", "or", "but", "of", "to", "in", "on", "for",
  "with", "at", "by", "from", "is", "are", "was", "were", "be", "been",
  "being", "it", "its", "this", "that", "these", "those", "i", "you", "we",
  "they", "he", "she", "them", "his", "her", "their", "my", "your", "our",
  "as", "so", "if", "then", "than", "can", "will", "would", "should",
  "could", "may", "might", "do", "does", "did", "have", "has", "had",
  "not", "no", "yes", "just", "very", "really", "about", "up", "down",
  "out", "into", "over", "under", "again", "after", "before", "between",
  "more", "most", "some", "any", "all", "each", "every", "both", "few",
  "there", "here", "what", "when", "where", "which", "who", "whom", "why",
  "how", "get", "got", "make", "made", "like", "one", "two", "let", "us",
]);

/** Posts below this length are too short for the statistical scan. */
const MIN_SUSPICIOUS_LENGTH = 120;
/** Sum of weighted signals at or above which a post reads machine-made. */
const REVIEW_SCORE = 6;
/** Em/en-dashes beyond this many count as a machine-typing tell. */
const EMDASH_SIGNAL_COUNT = 3;

/** Count distinct stock transitions (each phrase at most once). */
function countPhrases(lower: string, phrases: string[]): number {
  let hits = 0;
  for (const phrase of phrases) {
    if (lower.includes(phrase)) {
      hits++;
    }
  }
  return hits;
}

/** Word-length of each sentence (split on terminal punctuation). */
function sentenceLengths(text: string): number[] {
  return text
    .split(/[.!?]+/)
    .map((s) => s.trim().split(/\s+/).filter(Boolean).length)
    .filter((n) => n > 0);
}

/**
 * Scan post/comment/story text for signs of AI generation.
 *
 * Two tiers, deliberately: text that identifies itself as AI-generated is
 * BLOCKED outright (there is no innocent reading of "this was written by
 * ChatGPT"), while text that merely *reads* machine-made — stacked
 * formulaic phrasing, uniform sentence lengths, em-dash overuse, listicle
 * skeletons, canned hedges, heavy word repetition — is scored and sent to
 * the human review queue, never auto-blocked, so genuine human writing is
 * never rejected on a hunch. The reason names exactly which signals tripped
 * the scan so the admin queue can judge the flag at a glance.
 */
export function scanText(content: string): AiScanResult {
  const text = content.trim();
  if (text.length === 0) {
    return { status: "clean" };
  }
  for (const pattern of HARD_BLOCK_TEXT) {
    if (pattern.test(text)) {
      return {
        status: "blocked",
        reason: "This reads like AI-generated text, which isn't allowed on PureWire.",
      };
    }
  }
  if (text.length < MIN_SUSPICIOUS_LENGTH) {
    return { status: "clean" };
  }
  const lower = text.toLowerCase();
  const signals: string[] = [];
  let score = 0;

  const formulaic = countPhrases(lower, FORMULAIC_PHRASES);
  if (formulaic >= 3) {
    score += formulaic;
    signals.push(`formulaic phrasing ×${formulaic}`);
  }

  const hedges = countPhrases(lower, HEDGING_PHRASES);
  if (hedges >= 2) {
    score += hedges;
    signals.push(`${hedges} canned hedges`);
  }

  const listicle = countPhrases(lower, LISTICLE_OPENERS);
  if (listicle >= 3) {
    score += 3;
    signals.push(`listicle structure (${listicle} openers)`);
  }

  // Machine text types with regular rhythm: sentences of near-identical
  // length. Humans vary; a low coefficient of variation across several
  // sentences is a strong tell.
  const lengths = sentenceLengths(text);
  if (lengths.length >= 4) {
    const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length;
    if (mean >= 8 && mean <= 30) {
      const variance =
        lengths.reduce((acc, n) => acc + (n - mean) ** 2, 0) / lengths.length;
      const cv = Math.sqrt(variance) / mean;
      if (cv < 0.45) {
        score += 3;
        signals.push("uniform sentence lengths");
      }
    }
  }

  // Em/en-dash overuse: a human rarely chains several in one post.
  const dashes = (text.match(/[—–]/g) ?? []).length;
  if (dashes >= EMDASH_SIGNAL_COUNT) {
    score += Math.min(dashes, 6);
    signals.push(`${dashes} em-dashes`);
  }

  // One non-stopword repeated heavily is the signature of padded output.
  const words = text.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
  if (words.length >= 30) {
    const counts = new Map<string, number>();
    for (const w of words) {
      if (STOP_WORDS.has(w)) continue;
      counts.set(w, (counts.get(w) ?? 0) + 1);
    }
    let top = 0;
    for (const c of counts.values()) top = Math.max(top, c);
    if (top >= 4 && top / words.length >= 0.08) {
      score += 2;
      signals.push("heavy word repetition");
    }
  }

  if (score >= REVIEW_SCORE) {
    return {
      status: "review",
      reason: `${signals.join(" · ")} — flagged for a human check.`,
    };
  }
  return { status: "clean" };
}

/**
 * Shared validator for the media-scan verdict passed from the client into
 * the post/story mutations. Lives here so both callers stay in sync.
 */
export const AI_MEDIA_STATUS = v.union(
  v.literal("clean"),
  v.literal("review"),
  v.literal("blocked"),
);

export type AiMediaStatus =
  | "clean"
  | "review"
  | "blocked";

/**
 * Structured evidence from the multi-signal media assessment. Every signal
 * the scanner examined — byte-level metadata, Content Credentials
 * provenance, and OCR-racism — is recorded here so the admin review queue
 * can show exactly what was found and why the post was flagged, blocked,
 * or cleared.
 */
export interface AiMediaEvidence {
  /** The byte-level scan verdict: which generator marker was found (if any),
   * or "clean" when no known AI tool metadata was present. */
  byteScan: { status: "clean" | "review" | "blocked"; reason?: string };
  /** Content Credentials (C2PA) provenance from the file's manifest, when
   * present. Null when C2PA was absent or unreadable. */
  c2pa: { humanCapture: boolean; claimGenerator?: string } | null;
  /** Racism check on OCR-extracted text from image metadata (phone-OCR'd
   * screenshot descriptions, EXIF captions, PNG text chunks). Null when
   * no text was extracted or the text was clean. */
  ocrRacism: { status: "review" | "blocked"; reason: string } | null;
}

export type ScanMediaForAiResult =
  | { status: "clean"; c2paVerifiedHuman?: boolean; c2paClaimGenerator?: string; evidence: AiMediaEvidence }
  | { status: "review"; reason: string; evidence: AiMediaEvidence }
  | { status: "blocked"; reason: string; evidence: AiMediaEvidence };

/**
 * Scan every image in a media list by reading its bytes from storage.
 * Runs as an action because `storage.get` is only available in actions.
 * Mutations call this via `ctx.runAction`.
 */
export const scanMediaForAi = action({
  args: {
    media: v.array(
      v.object({
        // Dual-mode: a Convex storage id (legacy/fallback) OR an external
        // Cloudinary URL (primary path once CLOUDINARY_* is configured).
        storageId: v.optional(v.id("_storage")),
        url: v.optional(v.string()),
        kind: v.string(),
      }),
    ),
  },
  returns: v.union(
    v.object({
      status: v.literal("clean"),
      c2paVerifiedHuman: v.optional(v.boolean()),
      c2paClaimGenerator: v.optional(v.string()),
      evidence: v.any(),
    }),
    v.object({ status: v.literal("review"), reason: v.string(), evidence: v.any() }),
    v.object({ status: v.literal("blocked"), reason: v.string(), evidence: v.any() }),
  ),
  handler: async (ctx, { media }): Promise<ScanMediaForAiResult> => {
    let anyHumanCapture = false;
    let c2paClaimGenerator: string | undefined;
    // Build the evidence object across all items, capturing the first
    // non-clean signal that decided the verdict.
    const evidence: AiMediaEvidence = {
      byteScan: { status: "clean" },
      c2pa: null,
      ocrRacism: null,
    };
    for (const item of media) {
      let bytes: ArrayBuffer | null = null;
      if (item.url !== undefined) {
        const res = await fetch(item.url);
        if (res.ok) {
          bytes = await res.arrayBuffer();
        }
      } else if (item.storageId !== undefined) {
        const blob = await ctx.storage.get(item.storageId);
        if (blob !== null) {
          bytes = await blob.arrayBuffer();
        }
      }
      if (bytes === null) {
        continue;
      }
      const result: AiScanResult =
        item.kind === "image"
          ? scanImageBytes(bytes)
          : scanMediaBytes(bytes);
      if (result.status !== "clean") {
        evidence.byteScan = { status: result.status, reason: result.reason };
        return { status: result.status, reason: result.reason ?? "Media flagged by the AI scan.", evidence };
      }
      // OCR-based racism check
      if (result.ocrText !== undefined && result.ocrText.length > 0) {
        const racism = scanForRacism(result.ocrText);
        if (racism.status === "blocked") {
          evidence.ocrRacism = { status: "blocked", reason: racism.reason };
          return { status: "blocked", reason: `Racism detected in media text — ${racism.reason}`, evidence };
        }
        if (racism.status === "review") {
          evidence.ocrRacism = { status: "review", reason: racism.reason };
          return { status: "review", reason: `Media text flagged: ${racism.reason}`, evidence };
        }
      }
      // C2PA provenance � capture the first item that carries it (don't
      // overwrite, or the admin evidence panel only sees the last item).
      const c2pa = (result as { c2pa?: C2paInfo }).c2pa;
      if (c2pa !== undefined && evidence.c2pa === null) {
        evidence.c2pa = {
          humanCapture: c2pa.humanCapture === true,
          claimGenerator: c2pa.claimGenerator,
        };
        if (c2pa.humanCapture === true) {
          anyHumanCapture = true;
        }
        if (c2paClaimGenerator === undefined) {
          c2paClaimGenerator = c2pa.claimGenerator;
        }
      }
    }
    return { status: "clean", c2paVerifiedHuman: anyHumanCapture, c2paClaimGenerator, evidence };
  },
});
