import { v } from "convex/values";

import { action } from "./_generated/server";

/**
 * PureWire's anti-AI-content layer.
 *
 * The platform is built on original, human-made work — "say it anyway"
 * means *your* voice, not a machine's. This module scans posts, comments,
 * and stories before they go live:
 *
 * - Text that clearly identifies itself as AI-generated is blocked at
 *   creation with an honest message.
 * - Text that *reads* machine-made (heavy formulaic phrasing, including
 *   bare "as an AI" claims) is flagged for admin review instead of
 *   blocked, so genuine human writing is never rejected on a hunch.
 * - Images with generator metadata baked into the file (Stable Diffusion,
 *   Midjourney, DALL·E, NovelAI, ComfyUI, etc.) are blocked.
 *
 * Reading file bytes is only available inside Convex actions, so the
 * media scan is an action that mutations call via `ctx.runAction`.
 */

export type AiScanResult =
  | { status: "clean" }
  | { status: "review"; reason: string }
  | { status: "blocked"; reason: string };

/**
 * Messages that are overwhelmingly likely to be AI-generated. Each pattern
 * requires the full self-identifying phrase so legitimate human speech
 * like "as an AI researcher" or "I'm an AI engineer" is never blocked.
 */
const HARD_BLOCK_TEXT: RegExp[] = [
  /\bas an ai (?:language model|assistant|chatbot)\b/i,
  /\bi['’]?m an ai (?:language model|assistant|chatbot)\b/i,
  /\bi am an ai (?:language model|assistant|chatbot)\b/i,
  /\bthis (?:post|content|text|paragraph) (?:was|is) (?:written|generated|created|produced) by (?:an )?ai\b/i,
  /\bgenerated by (?:an )?(?:ai|chatgpt|gpt|dall[·e ]|midjourney)\b/i,
  /\bchatgpt (?:wrote|made|generated)\b/i,
];

/**
 * Formulaic phrasing that LLMs overuse — including bare "as an AI" and
 * "I'm an AI" claims, which are demoted here so that a human decides
 * instead of a false-positive block. A post that stacks several of these
 * reads machine-made and is flagged for admin review.
 */
const FORMULAIC_PHRASES = [
  "as an ai",
  "i'm an ai",
  "i am an ai",
  "as a language model",
  "moreover",
  "furthermore",
  "additionally",
  "in conclusion",
  "to summarize",
  "it is important to note",
  "it's important to",
  "it is worth noting",
  "delve",
  "underscore",
  "landscape",
  "in today's",
  "in the ever-evolving",
  "a testament to",
  "at the end of the day",
  "game-changer",
  "seamlessly",
  "cutting-edge",
  "let's dive",
  "it cannot be overstated",
  "it goes without saying",
  "notably,",
  "crucially,",
  "significantly,",
  "all in all",
  "overall,",
];

const MIN_SUSPICIOUS_LENGTH = 120;
const FORMULAIC_HITS_FOR_REVIEW = 5;

/** Scan post/comment/story text for signs of AI generation. */
export function scanText(content: string): AiScanResult {
  const text = content.trim();
  if (text.length === 0) {
    return { status: "clean" };
  }
  for (const pattern of HARD_BLOCK_TEXT) {
    if (pattern.test(text)) {
      return {
        status: "blocked",
        reason: "This reads like AI-generated text, which isn't allowed on PureWire.",
      };
    }
  }
  if (text.length >= MIN_SUSPICIOUS_LENGTH) {
    const lower = text.toLowerCase();
    let hits = 0;
    for (const phrase of FORMULAIC_PHRASES) {
      if (lower.includes(phrase)) {
        hits++;
      }
    }
    if (hits >= FORMULAIC_HITS_FOR_REVIEW) {
      return {
        status: "review",
        reason: "Heavy formulaic phrasing — flagged for a human check.",
      };
    }
  }
  return { status: "clean" };
}

/**
 * Generator markers embedded in AI image files — EXIF Software/ImageDescription
 * fields and PNG tEXt "parameters" chunks (Stable Diffusion WebUI, ComfyUI,
 * Midjourney, DALL·E, NovelAI, and friends). Scanned from the raw bytes.
 */
const IMAGE_GENERATOR_MARKERS = [
  "stable diffusion",
  "stable-diffusion",
  "midjourney",
  "dall-e",
  "dall e",
  "dall·e",
  "dalle",
  "novelai",
  "adobe firefly",
  "leonardo.ai",
  "leonardo ai",
  "dreamstudio",
  "sdxl",
  "flux 1",
  "flux.1",
  "playground ai",
  "playgroundai",
  "bing image creator",
  "craiyon",
  "hotpot.ai",
  "deepai",
  "nightcafe",
  "artbreeder",
  "wombo",
  "stability.ai",
  "fooocus",
  "comfyui",
  "a1111",
  "waifu-diffusion",
  "anything-v3",
  "dreamshaper",
  "realistic vision",
  "juggernaut",
  "sampler: ",
  "cfg scale",
  "negative prompt:",
  "seed: ",
];

/**
 * Shared validator for the media-scan verdict passed from the client into
 * the post/story mutations. Lives here so both callers stay in sync.
 */
export const AI_MEDIA_STATUS = v.union(
  v.literal("clean"),
  v.literal("review"),
  v.literal("blocked"),
);

export type AiMediaStatus =
  | "clean"
  | "review"
  | "blocked";

/**
 * Deepfake / face-manipulation tool markers found in image metadata or
 * container tags. Only tool-specific signatures are hard-blocked — a
 * generic word like "deepfake" or a consumer filter like "faceapp" is
 * demoted to the review tier so real photos are never rejected on a hunch.
 */
const DEEPFAKE_MARKERS = [
  "deepfacelab",
  "deep face lab",
  "faceswap",
  "face swap",
  "reface",
  "avatarify",
  "sadtalker",
  "roop",
  "inswap",
  "swapface",
];

/** Ambiguous wording/filter names — flagged for a human check, not blocked. */
const DEEPFAKE_REVIEW_MARKERS = ["deepfake", "faceapp"];

/**
 * Audio/video AI-generator signatures. Compound tool names are
 * hard-blocked; standalone brand words (Suno, ElevenLabs, Runway) are
 * demoted to review so legitimate metadata that merely mentions a brand
 * is never rejected automatically.
 */
const AV_GENERATOR_MARKERS = [
  "openai sora",
  "sora video",
  "sora-generated",
  "runwayml",
  "runway ml",
  "runway gen",
  "google veo",
  "veo 3",
  "pika labs",
  "pika.art",
  "pikavideo",
  "synthesia",
  "d-id.com",
  "d-id video",
  "luma dream machine",
  "lumaai",
  "kling ai",
  "klingai",
  "hailuo",
  "minimax video",
  "motion one",
  "musicgen",
  "riffusion",
  "fakeyou",
  "voice.ai",
  "lovoai",
  "resemble.ai",
  "murf.ai",
  "wellsaid",
  "play.ht",
  "tts-1",
  "tts-1-hd",
];

/** Standalone brand names — flagged for a human check, not blocked. */
const AV_REVIEW_MARKERS = [
  "suno",
  "elevenlabs",
  "eleven labs",
  "heygen",
  "hey gen",
  "runway",
  "pika",
  "udio",
  "descript",
  "ai voice",
];

const SCAN_HEAD_BYTES = 256 * 1024; // metadata lives at the head of the file

function bytesToLatin1(bytes: ArrayBuffer): string {
  const head = new Uint8Array(
    bytes,
    0,
    Math.min(bytes.byteLength, SCAN_HEAD_BYTES),
  );
  let text = "";
  for (let i = 0; i < head.length; i++) {
    text += String.fromCharCode(head[i]);
  }
  return text.toLowerCase();
}

/** Scan raw image bytes for generator and deepfake metadata markers. */
export function scanImageBytes(bytes: ArrayBuffer): AiScanResult {
  const lower = bytesToLatin1(bytes);
  for (const marker of IMAGE_GENERATOR_MARKERS) {
    if (lower.includes(marker)) {
      return {
        status: "blocked",
        reason: `This image carries AI-generator metadata (${marker.trim()}), which isn't allowed on PureWire.`,
      };
    }
  }
  for (const marker of DEEPFAKE_MARKERS) {
    if (lower.includes(marker)) {
      return {
        status: "blocked",
        reason: `This image looks deepfake-manipulated (${marker.trim()}), which isn't allowed on PureWire.`,
      };
    }
  }
  for (const marker of DEEPFAKE_REVIEW_MARKERS) {
    if (lower.includes(marker)) {
      return {
        status: "review",
        reason: `This image mentions a possible manipulation tool (${marker.trim()}) — flagged for a human check.`,
      };
    }
  }
  return { status: "clean" };
}

/** Scan raw audio/video bytes for AI-generator markers in container tags. */
export function scanMediaBytes(bytes: ArrayBuffer): AiScanResult {
  const lower = bytesToLatin1(bytes);
  for (const marker of AV_GENERATOR_MARKERS) {
    if (lower.includes(marker)) {
      return {
        status: "blocked",
        reason: `This media carries AI-generator metadata (${marker.trim()}), which isn't allowed on PureWire.`,
      };
    }
  }
  for (const marker of AV_REVIEW_MARKERS) {
    if (lower.includes(marker)) {
      return {
        status: "review",
        reason: `This media mentions a possible AI tool (${marker.trim()}) — flagged for a human check.`,
      };
    }
  }
  return { status: "clean" };
}

/**
 * Scan every image in a media list by reading its bytes from storage.
 * Runs as an action because `storage.get` is only available in actions.
 * Mutations call this via `ctx.runAction`.
 */
export const scanMediaForAi = action({
  args: {
    media: v.array(
      v.object({
        storageId: v.id("_storage"),
        kind: v.string(),
      }),
    ),
  },
  returns: v.union(
    v.object({ status: v.literal("clean") }),
    v.object({ status: v.literal("review"), reason: v.string() }),
    v.object({ status: v.literal("blocked"), reason: v.string() }),
  ),
  handler: async (ctx, { media }): Promise<AiScanResult> => {
    for (const item of media) {
      const blob = await ctx.storage.get(item.storageId);
      if (blob === null) {
        continue;
      }
      const bytes = await blob.arrayBuffer();
      const result: AiScanResult =
        item.kind === "image"
          ? scanImageBytes(bytes)
          : scanMediaBytes(bytes);
      if (result.status !== "clean") {
        return result;
      }
    }
    return { status: "clean" };
  },
});
