import { ConvexError, v } from "convex/values";

import { getAuthUserId } from "@convex-dev/auth/server";

import { AI_MEDIA_STATUS, scanText } from "./aiContent";
import { scanBlockedContent } from "./blocklist";
import { scanAdultContent } from "./adultContent";
import { scanForRacism } from "@/lib/racism-guard";
import { publicUser } from "./privacy";
import {
  enforceActive,
  enforceRateLimit,
  escalateSilently,
  hiddenAuthorIds,
  isSandboxed,
  silencedAuthorIds,
  testExclusionIds,
} from "./security";

import { paginationOptsValidator } from "convex/server";

import { action, internalMutation, mutation, query } from "./_generated/server";
import { api, internal } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { cloudinaryConfig } from "./mediaStorage";
import { parseUrlHost } from "./phishing";

/** The shape createStory/createStoryInternal both return. Explicitly typed
 * so the action's return never flows through the generated `internal`
 * namespace (TS7022 — see the same pattern in links.ts/media.ts). */
type CreateStoryResult =
  | { ok: true; storyId: Id<"stories"> }
  | { ok: false; error: string };

export const createStory = action({
  args: {
    media: v.object({
      // Dual-mode: a Convex storage id (legacy/fallback) OR an external
      // Cloudinary url + key (primary path once CLOUDINARY_* is set).
      storageId: v.optional(v.id("_storage")),
      url: v.optional(v.string()),
      key: v.optional(v.string()),
      kind: v.union(
        v.literal("image"),
        v.literal("video"),
        v.literal("audio"),
      ),
      stripped: v.optional(v.boolean()),
    }),
    caption: v.optional(v.string()),
    // Kept for API compatibility — the client still sends its scan verdict,
    // but this action IGNORES it and recomputes the verdict server-side by
    // reading the actual media bytes (see the handler). The internal
    // mutation is the only writer and receives only the verified verdict.
    aiMediaStatus: v.optional(AI_MEDIA_STATUS),
  },
  handler: async (ctx, { media, caption }): Promise<CreateStoryResult> => {
    // Same principle as createPost: the public gate is an action that
    // verifies the media bytes itself (actions can read storage, mutations
    // cannot), ignoring the client's reported verdict, then delegates the
    // atomic write to createStoryInternal. A direct caller claiming
    // aiMediaStatus:"clean" on AI-generated bytes gets the real verdict.
    const userId = await getAuthUserId(ctx);
    if (userId === null) {
      throw new Error("Not authenticated");
    }
    let verifiedStatus: "clean" | "review" | "blocked" = "clean";
    let aiEvidence: Record<string, unknown> | undefined;
    if (media.url !== undefined || media.storageId !== undefined) {
      const scan = await ctx.runAction(api.aiContent.scanMediaForAi, {
        media: [{ storageId: media.storageId, url: media.url, kind: media.kind }],
      });
      verifiedStatus = scan.status;
      aiEvidence = (scan as unknown as { evidence?: Record<string, unknown> }).evidence;
    }
    return (await ctx.runMutation(internal.stories.createStoryInternal, {
      media,
      caption,
      aiMediaStatus: verifiedStatus,
      aiEvidence,
    })) as CreateStoryResult;
  },
});

export const createStoryInternal = internalMutation({
  args: {
    media: v.object({
      // Dual-mode: a Convex storage id (legacy/fallback) OR an external
      // Cloudinary url + key (primary path once CLOUDINARY_* is set).
      storageId: v.optional(v.id("_storage")),
      url: v.optional(v.string()),
      key: v.optional(v.string()),
      kind: v.union(
        v.literal("image"),
        v.literal("video"),
        v.literal("audio"),
      ),
      stripped: v.optional(v.boolean()),
    }),
    caption: v.optional(v.string()),
    // Verdict from the server-side scan (the createStory action reads the
    // actual bytes via scanMediaForAi before delegating here).
    aiMediaStatus: v.optional(AI_MEDIA_STATUS),
    // Structured evidence from the multi-signal media assessment — byte
    // scan, C2PA provenance, OCR racism.
    aiEvidence: v.optional(v.any()),
  },
  handler: async (ctx, { media, caption, aiMediaStatus, aiEvidence }) => {
    const userId = await getAuthUserId(ctx);
    if (userId === null) {
      // ConvexError so the message survives the action → client boundary
      // (this mutation is invoked by the createStory action, never directly).
      throw new ConvexError("Not authenticated");
    }
    // ── Server-side media gate (same principle as createPost) ────────────
    // Each item must carry either a Convex storage id or an https URL on
    // PureWire's own media host — never both, never neither — and the URL
    // must pass the same adult/phishing blocklist that guards post text.
    const hasStorage = media.storageId !== undefined;
    const hasUrl = media.url !== undefined;
    if (hasStorage === hasUrl) {
      throw new ConvexError("Each media item needs either a storage id or a URL.");
    }
    if (hasUrl) {
      const url = media.url ?? "";
      let host: string | null = null;
      try {
        host = parseUrlHost(url);
      } catch {
        host = null;
      }
      if (host === null || !/^https:\/\//i.test(url)) {
        throw new ConvexError("Media URLs must be https.");
      }
      const cfg = cloudinaryConfig();
      if (cfg === null) {
        throw new ConvexError("Media URLs are disabled while storage is in fallback mode.");
      }
      const allowed =
        host === "res.cloudinary.com" || host.endsWith(".res.cloudinary.com");
      if (!allowed) {
        throw new ConvexError("Media must be hosted by PureWire's media provider.");
      }
      const mediaScan = await scanBlockedContent(ctx, url);
      if (mediaScan.status === "blocked") {
        await escalateSilently(ctx, userId, 3, "scam", "phish-block-media");
        return {
          ok: false,
          error:
            mediaScan.message ??
            "That media link is blocked on PureWire — nothing may link to adult platforms or phishing sites.",
        };
      }
      if (mediaScan.status === "review") {
        await escalateSilently(ctx, userId, 2, "scam", "phish-review-media");
      }
    }
    // Quiet sandbox: the story is accepted so nothing looks wrong, but it
    // stays invisible to everyone else until a human reviews the account.
    if (await isSandboxed(ctx, userId)) {
      const storyId = await ctx.db.insert("stories", {
        authorId: userId,
        media,
        caption,
        expiresAt: Date.now() + 24 * 3600_000,
        aiStatus: "clean",
        aiEvidence,
      });
      if (media.kind === "video") {
        await ctx.scheduler.runAfter(
          0,
          internal.videoStrip.stripVideoMetadataInternal,
          { storyId, media: [media] },
        );
      }
      return { ok: true, storyId };
    }
    await enforceActive(ctx, userId);
    await enforceRateLimit(ctx, userId, "post");
    const captionScan = caption !== undefined ? scanText(caption) : null;
    const phishScan =
      caption !== undefined ? await scanBlockedContent(ctx, caption) : null;
    if (phishScan?.status === "blocked") {
      await escalateSilently(ctx, userId, 3, "scam", "phish-block-story");
      return {
        ok: false,
        error:
          phishScan.message ??
          "That looks like a phishing or scam link — nothing on PureWire may try to steal accounts, money, or personal information.",
      };
    }
    const adultScan = caption !== undefined ? scanAdultContent(caption) : null;
    if (adultScan?.status === "blocked") {
      await escalateSilently(ctx, userId, 3, "scam", "adult-solicitation-story");
      return {
        ok: false,
        error: adultScan.message ?? "Sexual solicitation is not allowed on PureWire.",
      };
    }
    // Racism scan on the story caption: same three-tier pipeline as posts.
    // Blocked is rejected; review goes to the human queue alongside AI/
    // phishing signals.
    const racismScan = caption !== undefined ? scanForRacism(caption) : null;
    if (racismScan?.status === "blocked") {
      await escalateSilently(ctx, userId, 5, "harassment", "racism-block-story");
      return {
        ok: false,
        error: `That can't be posted — ${racismScan.reason}.`,
      };
    }
    if (captionScan?.status === "blocked") {
      // Rejected — and the rejection is itself an abuse signal. Escalated
      // INLINE with the structured result (a thrown error would roll the
      // flag back), so repeat offenders quietly shadowban.
      await escalateSilently(ctx, userId, 3, "ai", "ai-blocked");
      return {
        ok: false,
        error:
          "AI-generated content isn't allowed on PureWire. Say it in your own words.",
      };
    }
    if (aiMediaStatus === "blocked") {
      await escalateSilently(ctx, userId, 3, "ai", "ai-blocked");
      return {
        ok: false,
        error:
          "This media looks AI-generated, which isn't allowed on PureWire. Upload your own original work.",
      };
    }
    // A missing scan verdict means the client never ran the scan action —
    // route to the human review queue instead of trusting it as clean.
    const needsReview =
      captionScan?.status === "review" ||
      aiMediaStatus === undefined ||
      aiMediaStatus === "review" ||
      phishScan?.status === "review" ||
      racismScan?.status === "review";
    if (needsReview) {
      // Phishing-suspicious captions count as their own signal so the
      // Silenced tab shows the mix behind a quiet shadowban.
      await escalateSilently(
        ctx,
        userId,
        2,
        phishScan?.status === "review" ? "scam" : "ai",
        phishScan?.status === "review" ? "phish-review-story" : "ai-review",
      );
    }
    const expiresAt = Date.now() + 24 * 3600_000; // 24 hours
    const storyId = await ctx.db.insert("stories", {
      authorId: userId,
      media,
      caption,
      expiresAt,
      aiStatus: needsReview ? "review" : "clean",
      aiEvidence,
      // The review reason already carries the "Suspected phishing —"
      // prefix from scanForPhishing — used as-is, no double prefix.
      aiStatusReason:
        phishScan?.status === "review"
          ? (racismScan?.status === "review"
              ? `${phishScan.reason} · ${racismScan.reason}`
              : phishScan.reason)
          : racismScan?.status === "review"
            ? racismScan.reason
            : undefined,
    });
    if (media.kind === "video") {
      await ctx.scheduler.runAfter(
        0,
        internal.videoStrip.stripVideoMetadataInternal,
        { storyId, media: [media] },
      );
    }
    return { ok: true, storyId };
  },
});

export const listStories = query({
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (userId === null) {
      return [];
    }
    const follows = await ctx.db
      .query("follows")
      .withIndex("by_follower", (q) => q.eq("followerId", userId))
      .take(200);
    const authorIds = new Set([userId, ...follows.map((f) => f.followingId)]);
    const hidden = await hiddenAuthorIds(ctx, userId);
    const silenced = await silencedAuthorIds(ctx, userId);
    // Viewer-aware test exclusion: a live test run's stories never appear
    // on a real member's ring (a real member can't follow a QA account,
    // and even a stale follow row can't leak them), while QA accounts see
    // each other's fixtures.
    const testIds = new Set(await testExclusionIds(ctx, userId));
    const excluded = [...hidden, ...silenced];
    const me = await ctx.db.get(userId);
    const isAdmin = me?.role === "admin";
    const now = Date.now();
    const stories = await ctx.db
      .query("stories")
      .withIndex("by_expiration", (q) => q.gte("expiresAt", now))
      .take(200);
    const mine = stories.filter(
      (s) =>
        authorIds.has(s.authorId) &&
        !testIds.has(s.authorId) &&
        !excluded.includes(s.authorId) &&
        // Stories awaiting a human AI-review stay on the author's own ring
        // only — everyone else (admins included) sees them once approved.
        (s.aiStatus !== "review" || s.authorId === userId || isAdmin),
    );
    const withMeta = await Promise.all(
      mine.map(async (s) => {
        const author = await ctx.db.get(s.authorId);
        return {
          ...s,
          author: author
            ? {
                ...publicUser(author),
                avatarUrl:
                  author.avatarUrl ??
                  (author.avatarStorageId
                    ? await ctx.storage.getUrl(author.avatarStorageId)
                    : null),
              }
            : null,
          mediaUrl:
            s.media.url ??
            (s.media.storageId
              ? await ctx.storage.getUrl(s.media.storageId)
              : null),
          mediaKind: s.media.kind,
        };
      }),
    );
    // Group by author so each author appears once with their latest story.
    const byAuthor = new Map<string, (typeof withMeta)[number]>();
    for (const s of withMeta) {
      const key = s.authorId;
      const existing = byAuthor.get(key);
      if (!existing || s._creationTime > existing._creationTime) {
        byAuthor.set(key, s);
      }
    }
    return [...byAuthor.values()].sort((a, b) => b._creationTime - a._creationTime);
  },
});

/**
 * Record that the signed-in member viewed a story. One row per viewer per
 * story — re-viewing (or paging back to it) just bumps viewedAt, so a
 * viewer's name can't appear twice. Own views are never recorded: the
 * author already knows they looked.
 */
export const recordStoryView = mutation({
  args: { storyId: v.id("stories") },
  handler: async (ctx, { storyId }) => {
    const viewerId = await getAuthUserId(ctx);
    if (viewerId === null) {
      return;
    }
    const story = await ctx.db.get(storyId);
    // Only visible stories record views: a story awaiting human AI review
    // isn't on anyone else's ring, so a view of it is meaningless (and
    // would let a caller pad the author's list with fake views).
    if (
      story === null ||
      story.authorId === viewerId ||
      story.aiStatus === "review"
    ) {
      return;
    }
    const existing = await ctx.db
      .query("storyViews")
      .withIndex("by_story_viewer", (q) =>
        q.eq("storyId", storyId).eq("viewerId", viewerId),
      )
      .first();
    if (existing !== null) {
      await ctx.db.patch(existing._id, { viewedAt: Date.now() });
      return;
    }
    await ctx.db.insert("storyViews", {
      storyId,
      viewerId,
      viewedAt: Date.now(),
    });
  },
});

/**
 * Who viewed a story, newest first, paginated. ONLY the story's author (or
 * an admin) may see the list — a viewer never learns who else looked, and
 * non-authors get an empty page rather than an error (nothing to leak).
 */
export const listStoryViewers = query({
  args: {
    storyId: v.id("stories"),
    paginationOpts: paginationOptsValidator,
  },
  handler: async (ctx, { storyId, paginationOpts }) => {
    const viewerId = await getAuthUserId(ctx);
    if (viewerId === null) {
      return { page: [], isDone: true, continueCursor: "" };
    }
    const story = await ctx.db.get(storyId);
    if (story === null) {
      return { page: [], isDone: true, continueCursor: "" };
    }
    const me = await ctx.db.get(viewerId);
    const isAdmin = me?.role === "admin";
    if (story.authorId !== viewerId && !isAdmin) {
      return { page: [], isDone: true, continueCursor: "" };
    }
    // Order by most-recent view so the list matches the "viewed X ago"
    // labels — re-views bump viewedAt and bubble the viewer up.
    const result = await ctx.db
      .query("storyViews")
      .withIndex("by_story_viewed_at", (q) => q.eq("storyId", storyId))
      .order("desc")
      .paginate(paginationOpts);
    const page = await Promise.all(
      result.page.map(async (row) => {
        const viewer = await ctx.db.get(row.viewerId);
        if (viewer === null) {
          return null;
        }
        return {
          ...publicUser(viewer),
          avatarUrl:
            viewer.avatarUrl ??
            (viewer.avatarStorageId
              ? await ctx.storage.getUrl(viewer.avatarStorageId)
              : null),
          viewedAt: row.viewedAt,
        };
      }),
    );
    return {
      ...result,
      // Viewers whose accounts were removed mid-flight drop out silently.
      page: page.filter((v): v is NonNullable<typeof v> => v !== null),
    };
  },
});
