import { ConvexError, v } from "convex/values";

import { getAuthUserId } from "@convex-dev/auth/server";

import { AI_MEDIA_STATUS, scanText } from "./aiContent";
import { scanBlockedContent } from "./blocklist";
import { publicUser } from "./privacy";
import {
  enforceActive,
  enforceRateLimit,
  escalateSilently,
  hiddenAuthorIds,
  isSandboxed,
  silencedAuthorIds,
} from "./security";

import { action, internalMutation, query } from "./_generated/server";
import { api, internal } from "./_generated/api";
import type { Id } from "./_generated/dataModel";
import { cloudinaryConfig } from "./mediaStorage";
import { parseUrlHost } from "./phishing";

/** The shape createStory/createStoryInternal both return. Explicitly typed
 * so the action's return never flows through the generated `internal`
 * namespace (TS7022 — see the same pattern in links.ts/media.ts). */
type CreateStoryResult =
  | { ok: true; storyId: Id<"stories"> }
  | { ok: false; error: string };

export const createStory = action({
  args: {
    media: v.object({
      // Dual-mode: a Convex storage id (legacy/fallback) OR an external
      // Cloudinary url + key (primary path once CLOUDINARY_* is set).
      storageId: v.optional(v.id("_storage")),
      url: v.optional(v.string()),
      key: v.optional(v.string()),
      kind: v.union(
        v.literal("image"),
        v.literal("video"),
        v.literal("audio"),
      ),
      stripped: v.optional(v.boolean()),
    }),
    caption: v.optional(v.string()),
    // Kept for API compatibility — the client still sends its scan verdict,
    // but this action IGNORES it and recomputes the verdict server-side by
    // reading the actual media bytes (see the handler). The internal
    // mutation is the only writer and receives only the verified verdict.
    aiMediaStatus: v.optional(AI_MEDIA_STATUS),
  },
  handler: async (ctx, { media, caption }): Promise<CreateStoryResult> => {
    // Same principle as createPost: the public gate is an action that
    // verifies the media bytes itself (actions can read storage, mutations
    // cannot), ignoring the client's reported verdict, then delegates the
    // atomic write to createStoryInternal. A direct caller claiming
    // aiMediaStatus:"clean" on AI-generated bytes gets the real verdict.
    const userId = await getAuthUserId(ctx);
    if (userId === null) {
      throw new Error("Not authenticated");
    }
    let verifiedStatus: "clean" | "review" | "blocked" = "clean";
    if (media.url !== undefined || media.storageId !== undefined) {
      const scan = await ctx.runAction(api.aiContent.scanMediaForAi, {
        media: [{ storageId: media.storageId, url: media.url, kind: media.kind }],
      });
      verifiedStatus = scan.status;
    }
    return (await ctx.runMutation(internal.stories.createStoryInternal, {
      media,
      caption,
      aiMediaStatus: verifiedStatus,
    })) as CreateStoryResult;
  },
});

export const createStoryInternal = internalMutation({
  args: {
    media: v.object({
      // Dual-mode: a Convex storage id (legacy/fallback) OR an external
      // Cloudinary url + key (primary path once CLOUDINARY_* is set).
      storageId: v.optional(v.id("_storage")),
      url: v.optional(v.string()),
      key: v.optional(v.string()),
      kind: v.union(
        v.literal("image"),
        v.literal("video"),
        v.literal("audio"),
      ),
      stripped: v.optional(v.boolean()),
    }),
    caption: v.optional(v.string()),
    // Verdict from the server-side scan (the createStory action reads the
    // actual bytes via scanMediaForAi before delegating here).
    aiMediaStatus: v.optional(AI_MEDIA_STATUS),
  },
  handler: async (ctx, { media, caption, aiMediaStatus }) => {
    const userId = await getAuthUserId(ctx);
    if (userId === null) {
      // ConvexError so the message survives the action → client boundary
      // (this mutation is invoked by the createStory action, never directly).
      throw new ConvexError("Not authenticated");
    }
    // ── Server-side media gate (same principle as createPost) ────────────
    // Each item must carry either a Convex storage id or an https URL on
    // PureWire's own media host — never both, never neither — and the URL
    // must pass the same adult/phishing blocklist that guards post text.
    const hasStorage = media.storageId !== undefined;
    const hasUrl = media.url !== undefined;
    if (hasStorage === hasUrl) {
      throw new ConvexError("Each media item needs either a storage id or a URL.");
    }
    if (hasUrl) {
      const url = media.url ?? "";
      let host: string | null = null;
      try {
        host = parseUrlHost(url);
      } catch {
        host = null;
      }
      if (host === null || !/^https:\/\//i.test(url)) {
        throw new ConvexError("Media URLs must be https.");
      }
      const cfg = cloudinaryConfig();
      if (cfg === null) {
        throw new ConvexError("Media URLs are disabled while storage is in fallback mode.");
      }
      const allowed =
        host === "res.cloudinary.com" || host.endsWith(".res.cloudinary.com");
      if (!allowed) {
        throw new ConvexError("Media must be hosted by PureWire's media provider.");
      }
      const mediaScan = await scanBlockedContent(ctx, url);
      if (mediaScan.status === "blocked") {
        await escalateSilently(ctx, userId, 3, "scam", "phish-block-media");
        return {
          ok: false,
          error:
            mediaScan.message ??
            "That media link is blocked on PureWire — nothing may link to adult platforms or phishing sites.",
        };
      }
      if (mediaScan.status === "review") {
        await escalateSilently(ctx, userId, 2, "scam", "phish-review-media");
      }
    }
    // Quiet sandbox: the story is accepted so nothing looks wrong, but it
    // stays invisible to everyone else until a human reviews the account.
    if (await isSandboxed(ctx, userId)) {
      const storyId = await ctx.db.insert("stories", {
        authorId: userId,
        media,
        caption,
        expiresAt: Date.now() + 24 * 3600_000,
        aiStatus: "clean",
      });
      if (media.kind === "video") {
        await ctx.scheduler.runAfter(
          0,
          internal.videoStrip.stripVideoMetadataInternal,
          { storyId, media: [media] },
        );
      }
      return { ok: true, storyId };
    }
    await enforceActive(ctx, userId);
    await enforceRateLimit(ctx, userId, "post");
    const captionScan = caption !== undefined ? scanText(caption) : null;
    const phishScan =
      caption !== undefined ? await scanBlockedContent(ctx, caption) : null;
    if (phishScan?.status === "blocked") {
      // Rejected — and the rejection is itself an abuse signal, escalated
      // INLINE (a thrown error would roll the flag back), so repeat
      // scammers quietly shadowban.
      await escalateSilently(ctx, userId, 3, "scam", "phish-block-story");
      return {
        ok: false,
        // Platform-rule blocks (e.g. adult platforms) carry their own
        // sentence; scam signals keep the generic warning.
        error:
          phishScan.message ??
          "That looks like a phishing or scam link — nothing on PureWire may try to steal accounts, money, or personal information.",
      };
    }
    if (captionScan?.status === "blocked") {
      // Rejected — and the rejection is itself an abuse signal. Escalated
      // INLINE with the structured result (a thrown error would roll the
      // flag back), so repeat offenders quietly shadowban.
      await escalateSilently(ctx, userId, 3, "ai", "ai-blocked");
      return {
        ok: false,
        error:
          "AI-generated content isn't allowed on PureWire. Say it in your own words.",
      };
    }
    if (aiMediaStatus === "blocked") {
      await escalateSilently(ctx, userId, 3, "ai", "ai-blocked");
      return {
        ok: false,
        error:
          "This media looks AI-generated, which isn't allowed on PureWire. Upload your own original work.",
      };
    }
    // A missing scan verdict means the client never ran the scan action —
    // route to the human review queue instead of trusting it as clean.
    const needsReview =
      captionScan?.status === "review" ||
      aiMediaStatus === undefined ||
      aiMediaStatus === "review" ||
      phishScan?.status === "review";
    if (needsReview) {
      // Phishing-suspicious captions count as their own signal so the
      // Silenced tab shows the mix behind a quiet shadowban.
      await escalateSilently(
        ctx,
        userId,
        2,
        phishScan?.status === "review" ? "scam" : "ai",
        phishScan?.status === "review" ? "phish-review-story" : "ai-review",
      );
    }
    const expiresAt = Date.now() + 24 * 3600_000; // 24 hours
    const storyId = await ctx.db.insert("stories", {
      authorId: userId,
      media,
      caption,
      expiresAt,
      aiStatus: needsReview ? "review" : "clean",
      // The review reason already carries the "Suspected phishing —"
      // prefix from scanForPhishing — used as-is, no double prefix.
      aiStatusReason:
        phishScan?.status === "review" ? phishScan.reason : undefined,
    });
    if (media.kind === "video") {
      await ctx.scheduler.runAfter(
        0,
        internal.videoStrip.stripVideoMetadataInternal,
        { storyId, media: [media] },
      );
    }
    return { ok: true, storyId };
  },
});

export const listStories = query({
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (userId === null) {
      return [];
    }
    const follows = await ctx.db
      .query("follows")
      .withIndex("by_follower", (q) => q.eq("followerId", userId))
      .take(200);
    const authorIds = new Set([userId, ...follows.map((f) => f.followingId)]);
    const hidden = await hiddenAuthorIds(ctx, userId);
    const silenced = await silencedAuthorIds(ctx, userId);
    const excluded = [...hidden, ...silenced];
    const me = await ctx.db.get(userId);
    const isAdmin = me?.role === "admin";
    const now = Date.now();
    const stories = await ctx.db
      .query("stories")
      .withIndex("by_expiration", (q) => q.gte("expiresAt", now))
      .take(200);
    const mine = stories.filter(
      (s) =>
        authorIds.has(s.authorId) &&
        !excluded.includes(s.authorId) &&
        // Stories awaiting a human AI-review stay on the author's own ring
        // only — everyone else (admins included) sees them once approved.
        (s.aiStatus !== "review" || s.authorId === userId || isAdmin),
    );
    const withMeta = await Promise.all(
      mine.map(async (s) => {
        const author = await ctx.db.get(s.authorId);
        return {
          ...s,
          author: author
            ? {
                ...publicUser(author),
                avatarUrl:
                  author.avatarUrl ??
                  (author.avatarStorageId
                    ? await ctx.storage.getUrl(author.avatarStorageId)
                    : null),
              }
            : null,
          mediaUrl:
            s.media.url ??
            (s.media.storageId
              ? await ctx.storage.getUrl(s.media.storageId)
              : null),
          mediaKind: s.media.kind,
        };
      }),
    );
    // Group by author so each author appears once with their latest story.
    const byAuthor = new Map<string, (typeof withMeta)[number]>();
    for (const s of withMeta) {
      const key = s.authorId;
      const existing = byAuthor.get(key);
      if (!existing || s._creationTime > existing._creationTime) {
        byAuthor.set(key, s);
      }
    }
    return [...byAuthor.values()].sort((a, b) => b._creationTime - a._creationTime);
  },
});
