import { motion } from "framer-motion";
import {
  ArrowRight,
  BadgeCheck,
  FileText,
  Gavel,
  Handshake,
  Landmark,
  Lock,
  Mail,
  Scale,
  ShieldCheck,
  UserRound,
} from "lucide-react";
import { Link } from "react-router";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { useAuth } from "@/hooks/use-auth";

interface SectionBlock {
  heading?: string;
  body: string;
  list?: string[];
}

interface TermsSection {
  number: number;
  icon: typeof Scale;
  title: string;
  blocks: SectionBlock[];
}

/** The nine sections of the Terms, in document order. */
const sections: TermsSection[] = [
  {
    number: 1,
    icon: UserRound,
    title: "Eligibility & Verified Human Accounts",
    blocks: [
      {
        heading: "Human-Only Requirement",
        body: "PureWire is strictly for real human beings. Automated accounts, bot networks, synthetic entities, and scraped accounts are strictly forbidden.",
      },
      {
        heading: "Account Security",
        body: "Registration requires email verification. You are entirely responsible for maintaining the security of your account credentials and one-time verification tokens.",
      },
      {
        heading: "Account Termination & Abuse Budgets",
        body: "PureWire reserves the right to rate-limit, restrict, or quietly disable accounts that exhibit bot signals, spamming, harassment, or platform abuse, in accordance with Section 7 of these Terms.",
      },
    ],
  },
  {
    number: 2,
    icon: Handshake,
    title: "Creator Rights & Non-Exclusive License",
    blocks: [
      {
        heading: "Ownership Remains Yours",
        body: "You retain 100% full legal ownership of all original text, images, video, audio, and media (\u201cUser Content\u201d) that you post to PureWire. PureWire claims zero ownership over your creative output.",
      },
      {
        heading: "Non-Exclusive License to Host",
        body: "By uploading User Content to PureWire, you grant PureWire a worldwide, non-exclusive, royalty-free, revocable license solely to host, cache, display, transmit, and format your content for display within the Platform.",
      },
      {
        heading: "Right to Multi-Post Elsewhere",
        body: "Because this license is non-exclusive, you maintain the absolute legal right to publish, distribute, or post your content on any other platform, website, or offline medium at any time. No third-party platform or corporation holds exclusive distribution rights over content you voluntarily publish on PureWire.",
      },
    ],
  },
  {
    number: 3,
    icon: ShieldCheck,
    title: "The PureWire Standard (Acceptable Use Policy)",
    blocks: [
      {
        heading: "Freedom with a reason",
        body: "Freedom of expression requires protecting platform integrity so one person's freedom never strips away another's. You agree NOT to use PureWire to:",
        list: [
          "Steal Work / Impersonate: Upload media created by others without authorization, or impersonate any individual, brand, or entity.",
          "Upload AI Slop / Synthetic Media: Post text, images, audio, or video generated by AI engines or deepfake generators. PureWire enforces active fingerprinting to preserve human-only content.",
          "Harass, Stalk, or Dox: Engage in targeted harassment, stalk users, or publish non-public personal information (doxing).",
          "Scrape or Harvest: Deploy spiders, scrapers, headless browsers, or automated crawlers to capture user data, posts, or media.",
        ],
      },
    ],
  },
  {
    number: 4,
    icon: Gavel,
    title: "Section 230 Immunity & Interactive Computer Service Status",
    blocks: [
      {
        heading: "Statutory Immunity (47 U.S.C. § 230)",
        body: "PureWire operates as an \u201cinteractive computer service\u201d under Section 230 of the Communications Decency Act. PureWire is a distributor and host of user-generated content, not the publisher or speaker of statements posted by users.",
      },
      {
        heading: "User Liability",
        body: "Any liability, legal claims, or damages resulting from User Content belong solely to the individual user who created and posted that content.",
      },
      {
        heading: "Good Samaritan Protection",
        body: "Pursuant to 47 U.S.C. § 230(c)(2), PureWire maintains total legal immunity for any voluntary actions taken in good faith to restrict, limit, or remove content deemed harassing, abusive, violent, spammy, or otherwise objectionable.",
      },
    ],
  },
  {
    number: 5,
    icon: Mail,
    title: "Support Ticketing System & DMCA Safe Harbor",
    blocks: [
      {
        heading: "In-App Support & Reporting Ticket System",
        body: "All user inquiries, platform complaints, harassment reports, and policy violation claims must be submitted directly through the PureWire Support Ticket System inside the app. Reports automatically capture the specific post, account, and rule violation to ensure rapid review.",
      },
      {
        heading: "DMCA Takedown Notices",
        body: "If you believe copyrighted work has been uploaded without authorization, submit a compliant DMCA Notice through our in-app Ticket System or directly to our DMCA Agent at dmca@purewire.com.",
      },
      {
        heading: "Required Notice Details",
        body: "Physical or electronic signature, identification of the copyrighted work, URL/post ID of the infringing material on PureWire, valid contact information, and a statement under penalty of perjury that you are the rights holder or authorized agent.",
      },
      {
        heading: "Counter-Notification & Repeat Infringers",
        body: "Users who believe a takedown was issued in error may submit a formal Counter-Notification via the Ticket System. Accounts that repeatedly infringe copyrights will be permanently terminated.",
      },
    ],
  },
  {
    number: 6,
    icon: Lock,
    title: "PWA Distribution & Zero-Data Architecture",
    blocks: [
      {
        heading: "Direct Web Distribution",
        body: "PureWire is distributed directly through Progressive Web App (PWA) web standards, bypassing centralized app marketplace gatekeepers. Updates are pushed directly from our servers to your browser.",
      },
      {
        heading: "Zero Log Retention",
        body: "PureWire is built with privacy-first infrastructure. Server proxies discard IP addresses and metadata in memory. EXIF location metadata is automatically stripped from media uploads — and videos are remuxed on PureWire's servers so GPS and device atoms are removed before they are ever served.",
      },
      {
        heading: "Sessions & Sign-Out",
        body: "Your session persists until you sign out — up to 10 years on the permanent default, or 30 days if you opted out of \u201cKeep me signed in\u201d at sign-in. To keep you signed in without a password prompt on every visit, a sign-in credential (including its refresh token) is stored in your browser on each device. That credential is deleted when the session ends — by signing out, by ending the session from Settings, or by account deletion. On a shared device, sign out when you are done: signing out is the one action that clears your sign-in token from that machine, and you can end the session on every other device at any time from Settings.",
      },
      {
        heading: "Encrypted Direct Messages",
        body: "Direct messages are end-to-end encrypted. Message bodies and attachments are encrypted in the sender's browser with keys that exist only on the participants' devices; PureWire stores only ciphertext plus the routing metadata needed to deliver it. A built-in safety check runs on the sender's own device before a message is encrypted — links matching known scam patterns are blocked or flagged there, and no record of that check is kept — so the plaintext never leaves the device and the servers never see it. PureWire cannot read, scan, or produce the contents of a direct message in response to any request, including legal process, and deleting a conversation or account permanently removes every copy. Because keys are device-bound, a device that has never opened a conversation cannot decrypt it — that is a design guarantee, not a limitation.",
      },
      {
        heading: "No Backdoors & Report-Driven Moderation",
        body: "PureWire has no master key and no backdoor. Direct-message contents are end-to-end encrypted with keys that exist only on the participants' devices; the Platform stores only ciphertext, so neither PureWire, nor its administrators, nor any government or law-enforcement authority has the means to decrypt or produce a private message. Plain-text email addresses, precise locations, and tracking logs are never stored or exposed. Administrators act only when content is reported by another member or flagged by the Platform's automated safeguards — bots, farms, stolen or duplicated work, and AI-generated content — and even then they never see message contents, plain-text addresses, or coordinates. Every moderation action cites a principle of the PureWire Standard and is recorded in the audit trail.",
      },
      {
        heading: "Subpoenas & Records",
        body: "Because PureWire intentionally operates on zero-data retention, the Platform cannot produce user tracking logs, historical location records, plain-text email strings, or the contents of any direct message — to anyone, for any reason, including legal discovery, third-party subpoenas, or requests from any government or law-enforcement authority. There is no data of that kind to produce.",
      },
    ],
  },
  {
    number: 7,
    icon: Scale,
    title: "Limitation of Liability & Disclaimers",
    blocks: [
      {
        heading: "\u201cAS-IS\u201d Service",
        body: "PUREWIRE IS PROVIDED ON AN \u201cAS-IS\u201d AND \u201cAS-AVAILABLE\u201d BASIS. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.",
      },
      {
        heading: "NO CONSEQUENTIAL DAMAGES",
        body: "TO THE FULLEST EXTENT PERMITTED BY LAW, PUREWIRE AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR SPECIAL DAMAGES ARISING FROM YOUR USE OF THE PLATFORM.",
      },
    ],
  },
  {
    number: 8,
    icon: Landmark,
    title: "Governing Law, Jurisdiction & Binding Arbitration (Pennsylvania)",
    blocks: [
      {
        heading: "Governing Law",
        body: "These Terms and any dispute arising from the use of PureWire shall be governed by and construed in accordance with the laws of the Commonwealth of Pennsylvania, without regard to its conflict of law principles.",
      },
      {
        heading: "Exclusive Venue & Jurisdiction",
        body: "You agree that any legal action, suit, or proceeding not subject to arbitration shall be instituted exclusively in the state or federal courts located in Dauphin County, Pennsylvania (or the United States District Court for the Middle District of Pennsylvania, sitting in Harrisburg, PA).",
      },
      {
        heading: "Mandatory Individual Arbitration",
        body: "You agree that any dispute or claim arising out of your use of PureWire shall be settled through binding individual arbitration conducted in Harrisburg, Pennsylvania, rather than in court. Class action lawsuits, class action arbitrations, and private attorney general actions are strictly waived.",
      },
    ],
  },
  {
    number: 9,
    icon: FileText,
    title: "Legal Contact & Notices",
    blocks: [
      {
        heading: "Primary Channel",
        body: "Submit a ticket directly through the PureWire In-App Ticket System.",
      },
      {
        heading: "Official Legal Contact",
        body: "legal@purewire.com",
      },
      {
        heading: "DMCA Integrity Team",
        body: "dmca@purewire.com",
      },
      {
        heading: "Jurisdictional Seat",
        body: "Harrisburg, Dauphin County, Commonwealth of Pennsylvania",
      },
    ],
  },
];

export function Terms() {
  const { isAuthenticated } = useAuth();

  return (
    <div className="flex min-h-dvh flex-col">
      <header className="sticky top-0 z-40 border-b bg-background/80 backdrop-blur">
        <div className="mx-auto flex w-full max-w-3xl items-center justify-between px-4 py-4">
          <Link to="/" className="flex items-center gap-2">
            <img src="/logo.svg" alt="PureWire" className="size-8 rounded-xl" />
            <span className="font-bold tracking-tight">PureWire</span>
          </Link>
          <Button size="sm" asChild>
            <Link to={isAuthenticated ? "/home" : "/auth"}>
              {isAuthenticated ? "Open app" : "Get started"}
            </Link>
          </Button>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-12">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, ease: "easeOut" }}
          className="mb-10"
        >
          <span className="inline-flex items-center gap-1.5 rounded-full border border-oxide/40 bg-oxide/10 px-3 py-1 text-xs font-medium text-oxide dark:text-oxide-light">
            <Scale className="size-3" />
            Terms of Service
          </span>
          <h1 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">
            Freedom has{" "}
            <span className="brand-gradient-text">terms</span>
            <br />
            that protect it.
          </h1>
          <p className="mt-3 max-w-2xl text-base text-muted-foreground">
            PureWire is built on a simple deal: your freedom to say it anyway,
            in exchange for a platform worth saying it on. These Terms keep
            that deal honest — who can join, what stays yours, what&apos;s not
            allowed, and where disputes get resolved. Last updated August 3,
            2026. By using PureWire you agree to be bound by them.
          </p>
          <div className="mt-5 flex flex-wrap items-center gap-4 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1.5">
              <BadgeCheck className="size-3.5 text-moss" />
              Last Updated: August 3, 2026
            </span>
            <span className="inline-flex items-center gap-1.5">
              <BadgeCheck className="size-3.5 text-moss" />
              Effective Date: August 3, 2026
            </span>
          </div>
        </motion.div>

        {/* The acceptance clause — how using PureWire forms the agreement */}
        <Card className="mb-10 border-primary/20">
          <CardContent className="p-6">
            <p className="text-sm leading-relaxed text-muted-foreground">
              Welcome to PureWire (“Platform,” “we,” “us,” or “our”).
              PureWire is an independent progressive web application (PWA)
              engineered for authentic human connection, original content
              creation, and free expression — free from corporate tracking,
              advertising, and algorithmic manipulation.
            </p>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
              By accessing, installing, creating an account, or using the
              Platform, you (“User” or “you”) agree to be bound by these Terms
              of Service (“Terms”). If you do not agree to these Terms, do not
              use or install the Platform.
            </p>
          </CardContent>
        </Card>

        {/* The deal in one breath */}
        <section className="mb-10">
          <Card className="border-moss/30 bg-moss/5">
            <CardContent className="flex flex-col items-start gap-3 p-6 sm:flex-row sm:items-center">
              <div className="flex size-11 shrink-0 items-center justify-center rounded-xl brand-gradient-bg text-white">
                <Handshake className="size-5" />
              </div>
              <div>
                <h2 className="font-bold tracking-tight">Your work stays yours.</h2>
                <p className="text-sm text-muted-foreground">
                  You keep 100% ownership of everything you post. PureWire only
                  hosts it so others can see it — and you can take it anywhere,
                  anytime, because the license is non-exclusive.
                </p>
              </div>
            </CardContent>
          </Card>
        </section>

        {/* The nine sections */}
        <div className="flex flex-col gap-6">
          {sections.map((section, i) => (
            <motion.section
              key={section.number}
              initial={{ opacity: 0, y: 12 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-40px" }}
              transition={{ duration: 0.35, delay: Math.min(i * 0.04, 0.3) }}
            >
              <Card className="h-full">
                <CardHeader>
                  <CardTitle className="flex items-center gap-3 text-base">
                    <span className="flex size-8 shrink-0 items-center justify-center rounded-lg bg-oxide/15 text-oxide dark:text-oxide-light">
                      <section.icon className="size-4" />
                    </span>
                    <span>
                      <span className="mr-1.5 text-muted-foreground">
                        {section.number}.
                      </span>
                      {section.title}
                    </span>
                  </CardTitle>
                  {section.number === 3 ? (
                    <CardDescription>
                      The lines we draw so freedom can exist for everyone.
                    </CardDescription>
                  ) : null}
                  {section.number === 5 ? (
                    <CardDescription>
                      PureWire respects intellectual property rights and
                      enforces strict protections against stolen work and
                      platform abuse.
                    </CardDescription>
                  ) : null}
                </CardHeader>
                <CardContent className="flex flex-col gap-4">
                  {section.blocks.map((block, j) => (
                    <div key={j}>
                      {block.heading ? (
                        <p className="font-semibold leading-snug">
                          {block.heading}
                        </p>
                      ) : null}
                      <p className="text-sm text-muted-foreground">
                        {block.body}
                      </p>
                      {block.list ? (
                        <ul className="mt-2 flex flex-col gap-1.5">
                          {block.list.map((item, k) => (
                            <li
                              key={k}
                              className="flex items-start gap-2 text-sm text-muted-foreground"
                            >
                              <span className="mt-1.5 size-1.5 shrink-0 rounded-full bg-oxide" />
                              {item}
                            </li>
                          ))}
                        </ul>
                      ) : null}
                    </div>
                  ))}
                </CardContent>
              </Card>
            </motion.section>
          ))}
        </div>

        {/* CTA */}
        <Card className="mt-10 border-oxide/20 bg-oxide/5">
          <CardContent className="flex flex-col items-center gap-3 p-8 text-center">
            <ArrowRight className="size-8 text-oxide" />
            <h2 className="text-lg font-bold tracking-tight">
              Questions, reports, or takedowns?
            </h2>
            <p className="max-w-md text-sm text-muted-foreground">
              Every inquiry — support, harassment reports, policy violations,
              and DMCA notices — goes through the in-app Ticket System, which
              captures the post, account, and rule automatically.
            </p>
            <Button asChild>
              <Link to={isAuthenticated ? "/support" : "/auth"}>
                {isAuthenticated
                  ? "Open Support"
                  : "Sign in to open a ticket"}
              </Link>
            </Button>
          </CardContent>
        </Card>
      </main>

      <footer className="border-t">
        <div className="mx-auto flex w-full max-w-3xl flex-col items-center justify-between gap-3 px-4 py-8 text-sm text-muted-foreground sm:flex-row">
          <div className="flex items-center gap-2">
            <img src="/logo.svg" alt="PureWire" className="size-6 rounded-lg" />
            <span className="font-semibold text-foreground">PureWire</span>
          </div>
          <p>© {new Date().getFullYear()} PureWire. Say it anyway — no ads, ever.</p>
          <div className="flex items-center gap-4">
            <Link to="/privacy" className="hover:text-foreground hover:underline">
              Privacy
            </Link>
            <Link to="/support" className="hover:text-foreground hover:underline">
              Support
            </Link>
            <Link to="/" className="hover:text-foreground hover:underline">
              Home
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
